# Generated by Django 3.1.7 on 2021-04-16 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_auto_20210416_1136'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tojointhecourse',
            options={'verbose_name': 'Запись на курс', 'verbose_name_plural': 'Запись на курс'},
        ),
    ]
