# Generated by Django 3.1.7 on 2021-03-29 19:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('user_type', models.CharField(choices=[('ADMIN', 'ADMIN'), ('TEACHER', 'TEACHER'), ('MENTOR', 'MENTOR'), ('STUDENT', 'STUDENT'), ('CLIENT', 'CLIENT')], default='CLIENT', max_length=20, verbose_name='Тип пользователя')),
                ('email', models.EmailField(db_index=True, max_length=255, unique=True, verbose_name='Email')),
                ('first_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='First name')),
                ('last_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Last name')),
                ('telegram', models.CharField(blank=True, max_length=200, null=True, verbose_name='Telegram')),
                ('github', models.URLField(blank=True, max_length=150, null=True, verbose_name='Github')),
                ('instagram', models.CharField(blank=True, max_length=150, null=True, verbose_name='Instagram')),
                ('image', models.ImageField(blank=True, max_length=254, null=True, upload_to='media')),
                ('coins', models.IntegerField(blank=True, null=True, verbose_name='Geek coins')),
                ('date_joined', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date of join')),
                ('is_staff', models.BooleanField(default=False, verbose_name='Is staff')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is active')),
                ('phone_number', models.CharField(blank=True, max_length=200, null=True, verbose_name='Phone number')),
                ('birthday', models.DateField(blank=True, max_length=20, null=True, verbose_name='Birthday')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
            },
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(blank=True, choices=[('1', '1 месяц'), ('2', '2 месяц'), ('3', '3 месяц'), ('4', '4 месяц'), ('5', '5 месяц'), ('6', '6 месяц'), ('7', '7 месяц')], max_length=50, null=True, verbose_name='Месяц')),
                ('category', models.CharField(blank=True, choices=[('1', 'Помогите с темой курса'), ('2', 'Помогите с домашним заданием'), ('3', 'Сходим пообедать'), ('4', 'Кто хочет в магазин')], max_length=100, null=True, verbose_name='Категория')),
                ('group_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='Номер группы')),
                ('course_program', models.CharField(blank=True, choices=[('Back', 'Backend-разработчик'), ('Front', 'Frontend-разработчик'), ('IOS', 'iOS-разработчик'), ('Android', 'Android-разработка'), ('Ui/Ux', 'UX/UI Designer'), ('English', 'IT Английский')], max_length=100, null=True, verbose_name='Программа курса')),
                ('teacher', models.CharField(blank=True, choices=[('Back', 'Backend-разработчик'), ('Front', 'Frontend-разработчик'), ('IOS', 'iOS-разработчик'), ('Android', 'Android-разработка'), ('Ui/Ux', 'UX/UI Designer'), ('English', 'IT Английский')], max_length=100, null=True, verbose_name='Учитель')),
                ('problem_title', models.TextField(verbose_name='Дайте название проблеме')),
                ('problem_description', models.TextField(verbose_name='Опишите проблему')),
                ('file', models.FileField(blank=True, null=True, upload_to='media', verbose_name='Прикрепите файл')),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Запрос',
                'verbose_name_plural': 'Запросы',
            },
        ),
    ]
