# Generated by Django 3.1.7 on 2021-04-16 05:01

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210415_1129'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='material_url',
        ),
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=100, null=True), blank=True, null=True, size=5),
        ),
    ]
