# Generated by Django 3.1.7 on 2021-04-01 19:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_mentorcomment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mentorcomment',
            name='users',
        ),
        migrations.AddField(
            model_name='mentorcomment',
            name='users',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commented_users', to=settings.AUTH_USER_MODEL),
        ),
    ]
