# Generated by Django 3.1.7 on 2021-04-16 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_ismentor'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ismentor',
            options={'verbose_name': 'Стать ментором'},
        ),
    ]
