# Generated by Django 3.1.7 on 2021-04-16 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20210416_1321'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ismentor',
            options={'verbose_name': 'Стать ментором', 'verbose_name_plural': 'Стать ментором'},
        ),
    ]
