# Generated by Django 3.1.7 on 2021-04-12 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20210401_1952'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Request',
        ),
    ]
