# Generated by Django 3.1.7 on 2021-04-13 05:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, max_length=240, upload_to='media')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('date_of_event', models.DateField(blank=True, null=True)),
                ('time_of_event', models.CharField(blank=True, max_length=100, null=True)),
                ('location', models.CharField(max_length=255)),
                ('dop_location', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Меропрятие',
                'verbose_name_plural': 'Меропрятия',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(null=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('rate', models.IntegerField(blank=True, null=True)),
                ('events', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comments', to='events.event')),
            ],
            options={
                'verbose_name': 'Комментарий',
                'verbose_name_plural': 'Комментария',
                'ordering': ['created'],
            },
        ),
    ]
