# Generated by Django 3.1.7 on 2021-03-19 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_delete_ratingevent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name': 'Комментарий', 'verbose_name_plural': 'Комментария'},
        ),
    ]
