# Generated by Django 3.1.7 on 2021-03-21 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_auto_20210319_1555'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='created',
        ),
    ]
