# Generated by Django 3.1.7 on 2021-03-24 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_remove_event_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='ratting',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True),
        ),
    ]
