# Generated by Django 3.1.7 on 2021-03-30 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0010_remove_event_ratting'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='dop_location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
