# Generated by Django 3.1.7 on 2021-04-05 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0012_auto_20210330_1531'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='time_of_event',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='date_of_event',
            field=models.DateField(blank=True, null=True),
        ),
    ]
