# Generated by Django 3.1.7 on 2021-04-11 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_chat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
