# Generated by Django 3.1.7 on 2021-04-16 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_auto_20210411_1904'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='name',
            field=models.TextField(blank=True, null=True, verbose_name='Наименование чата'),
        ),
    ]
