# Generated by Django 3.1.7 on 2021-04-04 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='level',
            name='level_number',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
