# Generated by Django 3.1.7 on 2021-04-13 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_auto_20210413_1128'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='homework',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
