# Generated by Django 3.1.7 on 2021-04-16 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_auto_20210416_1321'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='grouplevel',
            options={'verbose_name': 'Уровень группы', 'verbose_name_plural': 'Уровень группы'},
        ),
    ]
