# Generated by Django 3.1.7 on 2021-04-12 16:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0002_level_level_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='user',
        ),
        migrations.CreateModel(
            name='GroupLevel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('month', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='group_level', to='courses.level')),
                ('students', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='group_students', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
