# Generated by Django 3.1.7 on 2021-05-06 18:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0004_auto_20210423_0002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grouplevel',
            name='students',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='group_students', to=settings.AUTH_USER_MODEL),
        ),
    ]
