# Generated by Django 3.1.7 on 2021-04-11 20:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(blank=True, max_length=50, null=True, verbose_name='Месяц')),
                ('category', models.CharField(blank=True, choices=[('1', 'Помогите с темой курса'), ('2', 'Помогите с домашним заданием'), ('3', 'Сходим пообедать'), ('4', 'Кто хочет в магазин')], max_length=100, null=True, verbose_name='Категория')),
                ('group_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='Номер группы')),
                ('course_program', models.CharField(blank=True, max_length=100, null=True, verbose_name='Программа курса')),
                ('teacher', models.CharField(blank=True, max_length=100, null=True, verbose_name='Учитель')),
                ('problem_title', models.TextField(verbose_name='Название запроса')),
                ('problem_description', models.TextField(verbose_name='Описание запроса')),
                ('file', models.FileField(blank=True, null=True, upload_to='media', verbose_name='Прикрепите файл')),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Запрос',
                'verbose_name_plural': 'Запросы',
            },
        ),
    ]
