# Generated by Django 3.1.7 on 2021-04-13 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(blank=True, max_length=50, null=True, verbose_name='Текст уведомления')),
                ('type', models.CharField(blank=True, max_length=100, null=True, verbose_name='Категория уведолмения')),
                ('created', models.DateTimeField(auto_now=True)),
                ('recieved_date', models.DateTimeField(auto_now=True)),
                ('is_read', models.BooleanField(blank=True, default=None, null=True, verbose_name='Прочитано')),
                ('is_match', models.BooleanField(blank=True, max_length=100, null=True, verbose_name='Программа курса')),
                ('is_read_by_mentor', models.BooleanField(default=None, null=True)),
            ],
            options={
                'verbose_name': 'Уведомление',
                'verbose_name_plural': 'Уведомления',
            },
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(blank=True, max_length=50, null=True, verbose_name='Месяц')),
                ('category', models.CharField(blank=True, max_length=100, null=True, verbose_name='Категория')),
                ('group_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='Номер группы')),
                ('course_program', models.CharField(blank=True, max_length=100, null=True, verbose_name='Программа курса')),
                ('teacher', models.CharField(blank=True, max_length=100, null=True, verbose_name='Учитель')),
                ('problem_title', models.TextField(verbose_name='Название запроса')),
                ('problem_description', models.TextField(verbose_name='Описание запроса')),
                ('file', models.FileField(blank=True, null=True, upload_to='media', verbose_name='Прикрепите файл')),
            ],
            options={
                'verbose_name': 'Запрос',
                'verbose_name_plural': 'Запросы',
            },
        ),
    ]
