# Generated by Django 3.1.7 on 2021-04-12 16:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('requests', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='category',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Категория'),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(blank=True, max_length=50, null=True, verbose_name='Текст уведомления')),
                ('type', models.CharField(blank=True, max_length=100, null=True, verbose_name='Категория уведолмения')),
                ('created', models.DateTimeField(auto_now=True)),
                ('recieved_date', models.DateTimeField(auto_now=True)),
                ('is_read', models.BooleanField(blank=True, default=None, null=True, verbose_name='Прочитано')),
                ('is_match', models.BooleanField(blank=True, max_length=100, null=True, verbose_name='Программа курса')),
                ('is_read_by_mentor', models.BooleanField(default=None, null=True)),
                ('recipients', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notification_recipients', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notification_sender', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Уведомление',
                'verbose_name_plural': 'Уведомления',
            },
        ),
    ]
