# Generated by Django 3.1.7 on 2021-04-20 12:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0003_auto_20210416_1321'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TableModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_here', models.BooleanField(blank=True, default=None, null=True, verbose_name='Посещаемость')),
                ('score', models.IntegerField(blank=True, default=None, null=True, verbose_name='Оценка за ДЗ')),
                ('date_of_lesson', models.DateField()),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson', to='courses.lesson', verbose_name='Урок')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='table_student', to=settings.AUTH_USER_MODEL, verbose_name='Студент')),
            ],
            options={
                'verbose_name': 'Посещаемость - Успеваемость',
                'verbose_name_plural': 'Посещаемость - Успеваемость',
                'ordering': ['id'],
            },
        ),
    ]
